repos:
# exclude: ^vendor/

# ---- Pre-commit hooks ---- : Standard hook library
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  -   id: trailing-whitespace # strip out white spaces at end of lines
  -   id: end-of-file-fixer # ensure newline present at end of file
  -   id: check-yaml # checks yaml files for parseable syntax.
  -   id: check-json # checks json files for parseable syntax
  -   id: check-added-large-files # check for files above certain size (as likely to be data files)
      args: ['--maxkb=500']
  -   id: detect-private-key # detects the presence of private keys.
  -   id: check-case-conflict # check for files that would conflict in case-insensitive file systems.
  -   id: check-merge-conflict # check for files that contain merge conflict strings.

# ----- Detect-secrets - Detects high entropy strings that are likely to be passwords.
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        exclude: .*/tests/.*|^\.cruft\.json$|.*ipynb # detect secrets flags interpreter hashes in the ipynb JSON files

# ----- black - code formatting
- repo: https://github.com/psf/black
  rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
    - id: black
      name: black - consistent Python code formatting (auto-fixes)
      language_version: python # Should be a command that runs python3.6+

# ----- flake8 - python linting
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      name: flake8 - Python linting

# ----- isort - imports sorting
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort - Sort Python imports (auto-fixes)
      types: [ cython, pyi, python ]
      args: [ "--profile", "black", "--filter-files" ]

# ----- pydocstyle - ensure consistency of docstrings
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
    - id: pydocstyle
      args:
      - --ignore=D107,D203,D204,D213

# ----- poetry - consistency checks during precommit
-   repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
